# Este workflow generara versiones y releases autom√°ticamente al pushear a main.
name: Release Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch: # <- Boton manual en GitHub

jobs:
  call-release:
    name: Call Shared Release
    uses: lyoss-usm/workflows/.github/workflows/semantic-release.yml@main
    secrets: inherit # Esto usa los secretos del repo o de la organizacion. (GH_PAT es requerido)
